spring.application.name=streamgame

# URL
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.max-lifetime=600000

# Twitch4J
twitch.client.id=
twitch.client.secret=
twitch.bot.access-token=
twitch.bot.refresh-token=
twitch.broadcaster.access-token=
twitch.broadcaster.refresh-token=
twitch.broadcaster-user-id=
twitch.channel.name=
